// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"omega/app/account/internal/biz"
	"omega/app/account/internal/conf"
	"omega/app/account/internal/data"
	"omega/app/account/internal/server"
	"omega/app/account/internal/service"
	"omega/pkg/database/dbengine"
	"omega/pkg/permission"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(registry)
	dbOptions := data.NewDBOptions(confData)
	dbEngine, err := dbengine.NewDBEngine(dbOptions)
	if err != nil {
		return nil, nil, err
	}
	permOptions := data.NewPermOptions(confData)
	permissionPermission, err := permission.NewPermission(dbEngine, permOptions)
	if err != nil {
		return nil, nil, err
	}
	dataData, err := data.NewData(dbEngine, permissionPermission, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	accountService := service.NewAccountService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	app := newApp(logger, registrar, grpcServer)
	return app, func() {
	}, nil
}
